##
# Project Title
#
# @file
# @version 0.1

main: main.cpp
	g++ -Wall -fdiagnostics-color -g main.cpp -o main

run: main
	./main

main2: main2.cpp
	g++ -Wall -fdiagnostics-color -g main2.cpp -o main2

run2: main2
	./main2
# end
